//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_Medicine
    {
        public Nullable<int> Bill_Medicine_Quantity { get; set; }
        public int Medicine_ID { get; set; }
        public int Bill_ID { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
