//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Bill_Medicine = new HashSet<Bill_Medicine>();
        }
    
        public int Medicine_ID { get; set; }
        public string Medicine_Name { get; set; }
        public Nullable<int> Medicine_Quantity { get; set; }
        public Nullable<decimal> Medicine_Price { get; set; }
        public Nullable<System.DateTime> Medicine_Expired { get; set; }
        public string Medicine_NXS { get; set; }
        public Nullable<int> Medicine_Category_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill_Medicine> Bill_Medicine { get; set; }
        public virtual Medicine_Category Medicine_Category { get; set; }
    }
}
